
// This file was auto-generated by ML.NET Model Builder. 

using Spam_ConsoleApp1;


// Create single instance of sample data from first line of dataset for model input
Spam.ModelInput sampleData = new Spam.ModelInput()
{
    Col1 = @"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",
    Col2 = @"",
    Col3 = @"",
    Col4 = @"",
};

// Make a single prediction on the sample data and print results
var predictionResult = Spam.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Col0 with predicted Col0 from sample data...\n\n");


Console.WriteLine($"Col0: {@"ham"}");
Console.WriteLine($"Col1: {@"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."}");
Console.WriteLine($"Col2: {@""}");
Console.WriteLine($"Col3: {@""}");
Console.WriteLine($"Col4: {@""}");


Console.WriteLine($"\n\nPredicted Col0: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

